import "../globals.css";
import Providers from "./providers";
import { ReactNode } from "react";
import { Metadata } from "next";
import { SidebarProvider } from "@/context/SidebarContext";
// ThemeProvider حذف شد چون در لایوت ریشه تعریف شده است

export const metadata: Metadata = {
  title: "فروشگاه آنلاین آمازون / داشبورد",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <SidebarProvider>
      <Providers>
        <div className="flex flex-col min-h-screen">
          {children}
        </div>
      </Providers>
    </SidebarProvider>
  );
}