// app/panel/layout.tsx (یا فایل لایه تودرتوی شما)
import "../globals.css";
import Providers from "./providers";
import { ReactNode } from "react";
import { Metadata } from "next";
import { SidebarProvider } from "@/context/SidebarContext";

export const metadata: Metadata = {
  title: "فروشگاه آنلاین آمازون / داشبورد",
  description: "Generated by create next app",
};

interface PanelLayoutProps {
  children: ReactNode;
}

export default function PanelLayout({ children }: PanelLayoutProps) {
  return (
    <div dir="rtl" className="w-full">
      <SidebarProvider>
        <Providers>
          {children}
        </Providers>
      </SidebarProvider>
    </div>
  );
}