// app/layout.tsx
import "../globals.css";
import Providers from "./providers";
import { ReactNode } from "react";
import { Metadata } from "next";
import { SidebarProvider } from "@/context/SidebarContext";

export const metadata: Metadata = {
  title: "فروشگاه آنلاین آمازون / داشبورد",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <SidebarProvider>
          <Providers>
            {children}
          </Providers>
        </SidebarProvider>
      </body>
    </html>
  );
}